name: sonabits
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase & Backend
  supabase_flutter: ^2.5.0

  # State Management
  provider: ^6.1.2

  # UI & Utilities
  google_fonts: ^6.2.1
  marquee: ^2.2.3
  flutter_lyric: ^2.0.4+6
  
  # Audio
  audioplayers: ^6.0.0

  # Local Storage
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3 
  dio: ^5.4.3+1        

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

# Konfigurasi untuk flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png" 
  min_sdk_android: 21

flutter:
  uses-material-design: true
